### ISSUE TITLE
jiraPrefix is not loading as expected

### ISSUE THREAD

**Issue by getmetorajesh** [digitalroute/cz-conventional-changelog-for-jira#24]
## Expected Behavior

When I set `jiraPrefix` in package.json config.commitizen
I expect the jira issue sample to use the entered prefix (Enter JIRA issue (DAZ-12345))

![image](https://user-images.githubusercontent.com/239905/116860608-2b0e2400-ac45-11eb-90af-3be57fdf987a.png)

## Current Behavior
Its always displaying the default prefix(DAZ).

**Comment by polarn** [comment]
closed because it should be fixed!
