### ISSUE TITLE
Customise ID position

### ISSUE THREAD

**Issue by j-m** [digitalroute/cz-conventional-changelog-for-jira#31]
AFAICT this plugin can only put the Jira ID at the start of your message. It would be amazing if you could offer a few variants, i.e.

## Prefix 
(default, current)
> feat(scope): JIRA-123 some commit message

## Suffix
Akin to the commonly used merge format `... (#1)`
> feat(scope): some commit message (JIRA-123)

## Body

To follow the Conventional Commit standard

>feat(scope): some commit message
>
>JIRA-123

**Comment by juliuscc** [comment]
I think that would be interesting. If you have it in the body you could do it like this:

```
feat(scope): some commit message

fixes: JIRA-123
```

I think some tools will better understand this. What do you think about that?

**Comment by j-m** [comment]
Good idea, maybe worth adding `prepend` and `append` options so people can add whatever wrappers they like, such as `[]` `()` `fixes:` `Refs `. 
And maybe the above options should be "start", "end", "body" respectively to avoid confusion. 
So we'd have:

Environment variable | package.json | Default | Options
| - | - | - | - |
CZ_JIRA_MODE | jiraMode | true | 
CZ_JIRA_OPTIONAL | jiraOptional | false | 
CZ_JIRA_PREFIX | jiraPrefix | "DAZ" | 
CZ_JIRA_LOCATION | jiraLocation | "start" | `start` or `end` or `body`
CZ_JIRA_PREPEND | jiraPrepend | "" | e.g. `Refs `, `fixes: `, `(`, `]`
CZ_JIRA_APPEND | jiraAppend | "" | e.g. `)`, `]`

**Comment by juliuscc** [comment]
Great idea!

**Comment by juliuscc** [comment]
Could you create some tests for this? Or possibly even a PR with an implementation?

**Comment by juliuscc** [comment]
I have one thought that popped into my mind. Could there be a case where teams want the issue number to be in the start of the whole line? Like this

> DAZ-243 feat: hello world

In that case, it might be confusing with only `start`. Could we possibly figure out more location words that are more specific?

**Comment by j-m** [comment]
Yeah I thought about that, too, but I don't think that would follow the conventional commits standard. Then again, if they wish to do so, we shouldn't be the ones to stop them.

How about we follow the same terminology as the standard and use `pre` and `post` so we'd call them `pre-type`, `pre-description`, `post-description`, and `footer`?

I'd love to! I'll have a look this weekend to see how much work it'd take, I'm pretty busy but I can't imagine this eating too much time

**Comment by juliuscc** [comment]
I think those are great names! Please go ahead 👍 

The only requirement is that you don't change the default behaviour of this library.
