### ISSUE TITLE
`jiraLocation` not reflected in writing phase

### ISSUE THREAD

**Issue by typeoneerror** [digitalroute/cz-conventional-changelog-for-jira#37]
With `jiraLocation` set to `pre-type`, and using `jiraPrepend` and `jiraAppend`, when you get to the following step, the configuration is not reflected in the preview.

With: 

```
  jiraLocation: 'pre-type',
  jiraPrepend: '[',
  jiraAppend: ']',
```

Actual:

```
Write a short, imperative tense description of the change:
  [------------------------------------------------------------------------] 56 chars left
   deps(npm): GS-6 resolves missing peer dependencies
```

Expected:

```
Write a short, imperative tense description of the change:
  [------------------------------------------------------------------------] 56 chars left
   [GS-6] deps(npm): resolves missing peer dependencies
```

**Comment by typeoneerror** [comment]
Note to self: need to update this:

https://github.com/digitalroute/cz-conventional-changelog-for-jira/blob/master/engine.js#L142-L151

**Comment by juliuscc** [comment]
Great catch! You linked to the correct code to fix this specific issue. However, I think we need to do more changes to `LimitedInputPrompt` in the case of `post-description`. In that case, we would need a `trailingLabel`. Could you create a PR for this?

**Comment by typeoneerror** [comment]
> Could you create a PR for this?

@juliuscc yeah, I think I have time in the next couple weeks. thanks for the add'l context.
