### ISSUE TITLE
Is there a way to detect lowercase jira id? 

### ISSUE THREAD

**Issue by kayqq** [digitalroute/cz-conventional-changelog-for-jira#38]
Currently the automatic branch name detection only works if the branch has a matching `jiraPrefix`
example:
- feature-daz-1234-branch-name // does not work
- feature-DAZ-1234-branch-name // detects DAZ-1234

**Comment by juliuscc** [comment]
Do you want to use lowercase for your branches but uppercase for your commit messages? Otherwise, I think it should work to set `jiraPrefix` to a lowercase word. Like `daz` instead of `DAZ`.

**Comment by wpater** [comment]
I think it could be helpful for developers which are working with `cz` to support both cases (`feature-daz-1234-branch-name` and `feature-DAZ-1234-branch-name`) and use uppercase in the commit message.

**Comment by juliuscc** [comment]
Yeah, it would make sense for it to be case-independent. I would welcome a PR that changes that. 👍

**Comment by wpater** [comment]
@juliuscc I am not a JS expert but this should be enough - https://github.com/digitalroute/cz-conventional-changelog-for-jira/pull/60
