### ISSUE TITLE
The Continous Deployment is broken

### ISSUE THREAD

**Issue by juliuscc** [digitalroute/cz-conventional-changelog-for-jira#54]
See the latest action: https://github.com/digitalroute/cz-conventional-changelog-for-jira/actions/runs/1682733074

The error seems to be this: `SemanticReleaseError: Cannot push to the Git repository.` and I don't know what has changed. Could we try resetting the secret `GITHUB_TOKEN` and see if that works? I recently deleted a private token that I thought was related to something completely else. It is very unlikely that my token was used for this repo but I am not 100% sure.

What do you think @polarn?

**Comment by Saeger** [comment]
I remember that we had a discussion with @polarn about switching the GITHUB_TOKEN, maybe it was done. I will check here.

**Comment by Saeger** [comment]
7.1.0 released and pipeline fixed.
