### ISSUE TITLE
Description prompt doesn't appear to respect JIRA_LOCATION

### ISSUE THREAD

**Issue by greenkiwi** [digitalroute/cz-conventional-changelog-for-jira#56]
I am just setting up this and really enjoying being able to connect the dots.  GitHub branch gets pulled into the commit and in the commit body.   I also really appreciate being able to specify the allowable scopes.  

One thing that is a bit strange is that the description always shows the JIRA ticket and doesn't allow me to use those characters.

Config:
```
{
  "maxHeaderWidth": 72,
  "path": "@digitalroute/cz-conventional-changelog-for-jira",
  "scopes": ["readme", "gha", "base"],
  "skipScope": false,
  "jiraLocation": "post-body"
}
```

The result is this:
![image](https://user-images.githubusercontent.com/54169/155909716-1fd51b4b-a9b4-48bf-999d-173b270a326f.png)

You can see that the final output has the jira item in the correct location, while the description input includes it in the line.

**Comment by juliuscc** [comment]
Ah yes, that is a bug. Would you like to submit a PR that fixes this?

**Comment by juliuscc** [comment]
It looks to me as if #57 fixes this issue. Do I understand it correctly?

**Comment by greenkiwi** [comment]
> Ah yes, that is a bug. Would you like to submit a PR that fixes this?

I was actually thinking that I'd try to take on the "lowercase" letters feature request if I get some time and we start using this on our team.
