### ISSUE TITLE
Post-body location seems not working

### ISSUE THREAD

**Issue by michalniemiec28** [digitalroute/cz-conventional-changelog-for-jira#72]
After setting `jiraLocation: 'post-body'` jira task is completely removed from commit.
I use dynamic configuration.
Configuration: 
![image](https://user-images.githubusercontent.com/23456622/195133661-da2de1e5-2037-4254-be3c-dca579babe6f.png)
CLI preview:
![image](https://user-images.githubusercontent.com/23456622/195133805-cf425eb6-e3b9-4c56-90e3-2e0ccc216c28.png)

**Comment by michalniemiec28** [comment]
I've checked with package.json configuration and it works fine, so it's not working only with dynamic configuration.

**Comment by juliuscc** [comment]
If you would press `y` and actually commit, does the commit message also omit the Jira-issue? Or is it only in the preview?

**Comment by michalniemiec28** [comment]
The message also omit an issue

**Comment by juliuscc** [comment]
Has this worked before? Do you know if the bug came with a recent update?

**Comment by juliuscc** [comment]
What version of `@digitalroute/cz-conventional-changelog-for-jira` are you using? We just pushed out an update like two days ago that could be related.

**Comment by michalniemiec28** [comment]
I use "@digitalroute/cz-conventional-changelog-for-jira": "^7.4.1"

**Comment by juliuscc** [comment]
Could you try exactly version 7.4.0? I suspect there might be a bug with 7.4.1

**Comment by michalniemiec28** [comment]
I've checked - the same situation

**Comment by juliuscc** [comment]
That is very strange to me. Would you be willing to investigate the bug and identify what could be wrong?

The jira issue should be added here: https://github.com/digitalroute/cz-conventional-changelog-for-jira/blob/master/engine.js#L267-L274

**Comment by michalniemiec28** [comment]
I think I know where the problem is. I assumed, according to docs, that `custom` function is going to override the defaults and it's not. I've noticed that there is no `jiraMode` in my config options so that's why footer had being omitted.

**Comment by michalniemiec28** [comment]
something like:
```js
var engine = require('./engine');
var defaults = require('./defaults');

module.exports = function(overridenOptions) {
  return engine({ ...defaults, ...overridenOptions });
};
```
could help
