### ISSUE TITLE
Allow skipping the type

### ISSUE THREAD

**Issue by s-hoff** [digitalroute/cz-conventional-changelog-for-jira#74]
We're trying to replace a custom commit-msg hook that used the branch names to add JIRA issues to the front of our commits with a commitizen/commitlint setup. Right now, we can't add any of the other of conventional-changelogs features yet but would like to already start using commitizen for our current convention.

Since there is already a skip option for most things, adding a skipType as well would allow us to just plug in commitizen right now.

**Comment by s-hoff** [comment]
I started working on this in #75 but its still printing `undefined` for the unspecified type. I can't finish this up right now but will once I get some time to do so.

**Comment by juliuscc** [comment]
I think this makes sense. I will approve it when your PR is done 😁
