### ISSUE TITLE
Not getting type of change in new version 7.5.0

### ISSUE THREAD

**Issue by VishalMathimaran** [digitalroute/cz-conventional-changelog-for-jira#76]
Not getting type of change option during commit from newer version. Is there a new flag for enabling this?
Screenshot -> [https://drive.google.com/file/d/1TpF4flxAhVagIrQyodH9Jq88UyPJjBMX/view?usp=sharing](url)

**Comment by juliuscc** [comment]
Hi! That looks like a bug to me. I think it's because of [this line](https://github.com/digitalroute/cz-conventional-changelog-for-jira/blob/17c7fdf9610ef7965cb3a75b049a1f2d3361c956/index.js#L33).

@s-hoff could you please submit a fix in a new PR?

**Comment by s-hoff** [comment]
Done, I must have somehow missed that.

Maybe its worth also covering this in the tests? Moving that into a function which would be used to build the options in the existing tests would mean they all cover regressions from introducing new options.

**Comment by juliuscc** [comment]
> Maybe its worth also covering this in the tests? Moving that into a function which would be used to build the options in the existing tests would mean they all cover regressions from introducing new options.

Yeah that makes sense! I agree. I wonder how though 🤔 It's easy to risk just creating tests that work exactly the same as the business logic.
